version: "3.7"

services:
    anaconda:
        image: continuumio/anaconda3
        command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
        volumes:
            - ./:/COVID
        ports:
            - 8888:8888

